/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projetooo;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo
 */
public class CadastroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form CadastroUsuario
     */
    public CadastroUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        txtSenha = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        registerUserButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(32767, 32767));
        setPreferredSize(new java.awt.Dimension(335, 430));

        jLabel1.setText("Usuario");

        jLabel2.setText("Senha");

        backButton.setBackground(new java.awt.Color(51, 51, 255));
        backButton.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Voltar");
        backButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        backButton.setBorderPainted(false);
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin1ActionPerformed(evt);
            }
        });

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        registerUserButton.setBackground(new java.awt.Color(51, 51, 255));
        registerUserButton.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        registerUserButton.setForeground(new java.awt.Color(255, 255, 255));
        registerUserButton.setText("Cadastrar Usuario");
        registerUserButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        registerUserButton.setBorderPainted(false);
        registerUserButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerUserButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Email");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(registerUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSenha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(registerUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin1ActionPerformed
        Login telaLogin = new Login();
        telaLogin.setVisible(true); // mostrar tela
        telaLogin.setLocationRelativeTo(null); //abrir no centro
        this.dispose();
    }//GEN-LAST:event_btnLogin1ActionPerformed

    private void registerUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerUserButtonActionPerformed
        List<String> camposRequeridos = new ArrayList<String>();
        String usuario = txtUsuario.getText();        
        String senha = txtSenha.getText();
        String email = txtEmail.getText();
        
        if("".equals(usuario)) {
            camposRequeridos.add("Usuario");
        }        
        if("".equals(senha)) {
            camposRequeridos.add("Senha");
        }        
        if("".equals(email)) {
            camposRequeridos.add("Email");
        }
        if(camposRequeridos.size() > 0 ){
            String erro = String.join(", ", camposRequeridos);
            JOptionPane.showMessageDialog(null,"Os campos " + erro + " são necessarios", "", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Connection conn = new mysqlConnector().conn;
        try {                
            Statement stmd = conn.createStatement();
            int rs = stmd.executeUpdate("INSERT INTO USER (USERNAME, PASSWORD, EMAIL) VALUES ('" + usuario + "', '" + senha + "', '" + email + "')");

            if(rs == 1){
                Inicio telaInicial = new Inicio();
                telaInicial.setVisible(true); // mostrar tela
                telaInicial.setLocationRelativeTo(null); //abrir no centro
                ResultSet generatedKeys = stmd.getGeneratedKeys();
                if (generatedKeys.next()) {
                    GlobalVariables.UserId = generatedKeys.getInt(1);
                }
                 
                this.dispose();
            } else{ 
                JOptionPane.showMessageDialog(null, "Usuário ou senha inválidos", "Erro de login", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Problema de connexão com Servidor", "Erro de login", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_registerUserButtonActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogin1;
    private javax.swing.JButton btnLogin10;
    private javax.swing.JButton btnLogin11;
    private javax.swing.JButton btnLogin12;
    private javax.swing.JButton btnLogin13;
    private javax.swing.JButton btnLogin14;
    private javax.swing.JButton btnLogin16;
    private javax.swing.JButton btnLogin17;
    private javax.swing.JButton btnLogin3;
    private javax.swing.JButton btnLogin4;
    private javax.swing.JButton btnLogin5;
    private javax.swing.JButton btnLogin6;
    private javax.swing.JButton btnLogin7;
    private javax.swing.JButton btnLogin8;
    private javax.swing.JButton btnLogin9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JPasswordField jpfSenha1;
    private javax.swing.JPasswordField jpfSenha2;
    private javax.swing.JPasswordField jpfSenha3;
    private javax.swing.JPasswordField jpfSenha4;
    private javax.swing.JPasswordField jpfSenha5;
    private javax.swing.JPasswordField jpfSenha6;
    private javax.swing.JPasswordField jpfSenha7;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbSenha1;
    private javax.swing.JLabel lbSenha2;
    private javax.swing.JLabel lbSenha3;
    private javax.swing.JLabel lbSenha4;
    private javax.swing.JLabel lbSenha5;
    private javax.swing.JLabel lbSenha6;
    private javax.swing.JLabel lbSenha7;
    private javax.swing.JLabel lbSubtitulo;
    private javax.swing.JLabel lbSubtitulo1;
    private javax.swing.JLabel lbSubtitulo2;
    private javax.swing.JLabel lbSubtitulo3;
    private javax.swing.JLabel lbSubtitulo4;
    private javax.swing.JLabel lbSubtitulo5;
    private javax.swing.JLabel lbSubtitulo6;
    private javax.swing.JLabel lbSubtitulo7;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbTitulo1;
    private javax.swing.JLabel lbTitulo2;
    private javax.swing.JLabel lbTitulo3;
    private javax.swing.JLabel lbTitulo4;
    private javax.swing.JLabel lbTitulo5;
    private javax.swing.JLabel lbTitulo6;
    private javax.swing.JLabel lbTitulo7;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JLabel lbUsuario1;
    private javax.swing.JLabel lbUsuario2;
    private javax.swing.JLabel lbUsuario3;
    private javax.swing.JLabel lbUsuario4;
    private javax.swing.JLabel lbUsuario5;
    private javax.swing.JLabel lbUsuario6;
    private javax.swing.JLabel lbUsuario7;
    private javax.swing.JButton registerUserButton;
    private javax.swing.JTextField txfUsuario;
    private javax.swing.JTextField txfUsuario2;
    private javax.swing.JTextField txfUsuario3;
    private javax.swing.JTextField txfUsuario4;
    private javax.swing.JTextField txfUsuario5;
    private javax.swing.JTextField txfUsuario6;
    private javax.swing.JTextField txfUsuario7;
    private javax.swing.JTextField txfUsuario9;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
